model:
  name: denoiser_diffusion
  sample_rate: 44100
  slice_length: 0.7430386 # Length of slice to get 2^15 samples
  in_dim: 1
  hidden_size: 512
  token_collect_size: 64
  num_blocks: 6
  num_heads: 8
  dropout: 0.0
  num_steps: 100
  schedulers: cosine
  amp: False

learning:
  batch_size: 12
  learning_rate: 0.0005
  weight_decay: 0.01
  epochs: 1000
  gradient_clip: 0.5
  beta_ema: 0.9999
  monitored_loss: Validation total loss
  dataset_path: data/music_samples/
  scheduler_type: 'one_cycle_lr'
  dataset_name: 'music_slice_dataset'
  eval_split_factor: 0.01

  loss_dict:
    loss_reconstruction: 0.01
    loss_mel: 1.0
    loss_mel_sub_1: 1.0
    loss_mel_sub_2: 1.0

mel_spec_config:
  n_fft: 2048
  hop_length: 512
  n_mels: 128
  pad_mode: reflect
  power: 1.0
  norm: "slaney"
  mel_scale: "htk"

mel_spec_sub_1_config:
  n_fft: 1024
  hop_length: 256
  n_mels: 128
  pad_mode: reflect
  power: 2.0
  norm: "slaney"
  mel_scale: "htk"

mel_spec_sub_2_config:
  n_fft: 512
  hop_length: 512
  n_mels: 64
  pad_mode: reflect
  power: 2.0
  norm: "slaney"
  mel_scale: "htk"