model:
  name: denoiser
  sample_rate: 44100
  slice_length: 0.7430386 # Length of slice to get 2^15 samples
  # slice_length: 5.0 # Length of slice to get 2^15 samples
  num_encoder_layers: 10
  num_decoder_layers: 10
  filter_size_encoder: 15
  filter_size_decoder: 5
  num_input_channels: 1
  num_filters: 16
  amp: True


learning:
  batch_size: 16
  learning_rate: 0.000
  weight_decay: 0.01
  epochs: 20
  gradient_clip: 0.5
  beta_ema: 0.9999
  monitored_loss: Validation total loss
  dataset_path: data/music_samples/
  scheduler_type: 'one_cycle_lr'
  dataset_name: 'music_slice_dataset'
  eval_split_factor: 0.01
  
  