model:
  name: denoiser_diffusion
  sample_rate: 44100
  slice_length: 0.7430386 # Length of slice to get 2^15 samples
  in_dim: 1
  hidden_size: 256
  token_collect_size: 128
  num_blocks: 6
  num_heads: 8
  dropout: 0.0
  num_steps: 10
  schedulers: cosine

learning:
  batch_size: 8
  learning_rate: 0.001
  weight_decay: 0.0
  epochs: 20
  gradient_clip: 0.5
  beta_ema: 0.9999
  monitored_loss: Validation total loss
  dataset_path: data/music_samples/
  scheduler_type: 'one_cycle_lr'
  dataset_name: 'music_slice_dataset'
  eval_split_factor: 0.01