model:
  name: lvl2_diff
  sample_rate: 44100
  slice_time: 0.7430386 # Length of slice to get 2^15 samples
  in_dim: 8
  hidden_size: 512
  token_collect_size: 1
  num_blocks: 6
  num_heads: 8
  dropout: 0.0
  num_steps: 300
  scheduler: linear
  amp: False
  collection_parameter: 1
  data_multiplier: 1.5


learning:
  batch_size: 6
  learning_rate: 0.0001
  weight_decay: 0.0001
  epochs: 30000
  gradient_clip: 0.5
  beta_ema: 0.9999
  monitored_loss: Validation total loss
  dataset_path: data/music_samples/
  scheduler_type: 'none'
  dataset_name: 'music_slice_dataset'
  eval_split_factor: 0.01
  preload_data_file_path: 'data/music_samples/002-datatensor_gen.pt'
  preload_metadata_file_path: 'data/music_samples/002-metadata_gen.pkl'
  slice_length: 4096


loss:

  noise_loss:
    weight: 1.0
    base_loss_type: 'l2_loss'
    phase_parameter: 1