model:
  name: lvl4_diff
  sample_rate: 44100
  slice_time: 0.18575965 # Length of slice to get 2^15 samples
  in_dim: 8
  hidden_size: 512
  token_collect_size: 64
  num_blocks: 6
  num_heads: 8
  dropout: 0.0
  num_steps: 10
  schedulers: cosine
  amp: False


learning:
  batch_size: 6
  learning_rate: 0.0001
  weight_decay: 0.0001
  epochs: 1000
  gradient_clip: 0.5
  beta_ema: 0.9999
  monitored_loss: Validation total loss
  dataset_path: data/music_samples/
  scheduler_type: 'none'
  dataset_name: 'music_slice_dataset'
  eval_split_factor: 0.01


loss:

  noise_loss:
    weight: 1.0
    base_loss_type: 'l2_loss'
    phase_parameter: 10