model:
  name: vqvae_lvl_1
  sample_rate: 44100
  slice_length: 0.7430386 # Length of slice to get 2^15 samples
  # slice_length: 5.0 # Length of slice to get 2^15 samples
  hidden_size: 32
  latent_width: 128
  latent_depth: 8
  beta_factor: 0.5
  vocabulary_size: 32768
  channel_dim_change_list: [2, 2, 2, 4, 4]

learning:
  batch_size: 8
  learning_rate: 0.001
  weight_decay: 0.0
  epochs: 20
  gradient_clip: 0.5
  beta_ema: 0.9999
  monitored_loss: Validation total loss
  dataset_path: data/music_samples/
  scheduler_type: 'one_cycle_lr'
  dataset_name: 'music_slice_dataset'
  eval_split_factor: 0.01

mel_spec_config:
  n_fft: 1024
  hop_length: 512
  n_mels: 128
  pad_mode: reflect
  power: 1.0
  norm: "slaney"
  mel_scale: "htk"
  