model:
  name: tvqvae_lvl_1
  sample_rate: 44100
  slice_time: 0.7430386 # Length of slice to get 2^15 samples
  hidden_size: 256
  latent_width: 128
  latent_depth: 8
  vocabulary_size: 8192
  num_transformer_layers_per_stage: 3
  channel_dim_change_list: [2, 2, 2, 2, 2, 2]
  amp: False
  input_channels: 1
  patch_collection_size: 32
  n_heads: 8

learning:
  batch_size: 4
  learning_rate: 0.0001
  weight_decay: 0.0
  epochs: 4000
  gradient_clip: 0.5
  beta_ema: 0.9999
  monitored_loss: Validation total loss
  dataset_path: data/music_samples/
  scheduler_type: 'none'
  dataset_name: 'music_slice_dataset'
  eval_split_factor: 0.01
  preload_data_file_path: 'data/music_samples/000-datatensor.pt'
  preload_metadata_file_path: 'data/music_samples/000-metadata.pkl'

loss:

  reconstruction_loss:
    weight: 1.00
    base_loss_type: 'l2_loss'
    phase_parameter: 1

  alignment_loss:
    weight: 0.5
    base_loss_type: 'l2_loss'

  commitment_loss:
    weight: 0.5
    base_loss_type: 'l2_loss'

  # melspec_loss_1:
  #   weight: 1.0
  #   base_loss_type: 'l1_loss'
  #   lin_start: 1.0
  #   lin_end: 1.0
    
  #   melspec_params:
  #     n_fft: 2048
  #     hop_length: 512
  #     n_mels: 128
  #     pad_mode: reflect
  #     power: 1.0
  #     norm: "slaney"
  #     mel_scale: "htk"

  # melspec_loss_2:
  #   weight: 1.0
  #   base_loss_type: 'l1_loss'
  #   lin_start: 1.0
  #   lin_end: 1.0

  #   melspec_params:
  #     n_fft: 1024
  #     hop_length: 256
  #     n_mels: 128
  #     pad_mode: reflect
  #     power: 2.0
  #     norm: "slaney"
  #     mel_scale: "htk"

  # melspec_loss_3:
  #   weight: 1.0
  #   base_loss_type: 'l1_loss'
  #   lin_start: 0.1
  #   lin_end: 20

  #   melspec_params:
  #     n_fft: 512
  #     hop_length: 512
  #     n_mels: 64
  #     pad_mode: reflect
  #     power: 1.0
  #     norm: "slaney"
  #     mel_scale: "htk"

  # melspec_loss_4:
  #   weight: 5.0
  #   base_loss_type: 'l1_loss'
  #   lin_start: 0.5
  #   lin_end: 10.0
    
  #   melspec_params:
  #     n_fft: 2048
  #     hop_length: 512
  #     n_mels: 128
  #     pad_mode: reflect
  #     power: 1.0
  #     norm: "slaney"
  #     mel_scale: "htk"

  # melspec_loss_5:
  #   weight: 5.0
  #   base_loss_type: 'l1_loss'
  #   lin_start: 0.1
  #   lin_end: 20

  #   melspec_params:
  #     n_fft: 512
  #     hop_length: 512
  #     n_mels: 64
  #     pad_mode: reflect
  #     power: 2.0
  #     norm: "slaney"
  #     mel_scale: "htk"
  